server:
  port: 32002
spring:
  application:
    name: uploadApplication
  datasource:
    url: jdbc:mysql://localhost:3306/yang_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ghr
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
base:
  staticPath: http://192.168.0.4:32002/static
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:32000/eureka/